import streamlit as st
import json
import pandas as pd
from datetime import datetime
from typing import Dict, List

# Mock classes for testing without API
class MockStartupEvaluator:
    def evaluate_startup(self, pitch_deck_path=None, form_data=None, investor_preferences=None):
        # Mock evaluation result
        return MockInvestmentMemo()
    
    def batch_evaluate(self, startup_data_list, investor_preferences=None):
        return [MockInvestmentMemo() for _ in startup_data_list]
    
    def generate_deal_note(self, memo):
        return f"""
# Investment Deal Note: {memo.startup_profile.company_name}

## Executive Summary
**Investment Score:** {memo.investment_score:.1f}/10
**Recommendation:** {memo.recommendation}
**Risk Level:** {memo.risk_assessment.risk_level.upper()}

## Team/Founder Summary
- **John Doe**: Tech entrepreneur with 5 years experience (Founder-Market Fit: 7.5/10)

## Market Analysis
- **Market Size:** $5,000,000,000
- **Growth Rate:** 15.0%
- **Competition Level:** medium
- **Key Players:** CompetitorA, CompetitorB

## Key Strengths
- Strong founder-market fit
- Large addressable market
- Revenue generating

## Key Concerns
- Competitive market landscape
- Scaling challenges ahead

---
*Generated by AI Startup Evaluator on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

class MockInvestmentMemo:
    def __init__(self):
        self.investment_score = 7.8
        self.recommendation = "BUY - Good opportunity with acceptable risk profile"
        self.key_strengths = ["Strong founder-market fit", "Large addressable market", "Revenue generating"]
        self.key_concerns = ["Competitive market landscape", "Scaling challenges ahead"]
        self.risk_assessment = MockRiskAssessment()
        self.startup_profile = MockStartupProfile()

class MockRiskAssessment:
    def __init__(self):
        self.risk_level = "medium"
        self.risk_factors = ["High competition", "Market saturation"]

class MockStartupProfile:
    def __init__(self):
        self.company_name = "TechStartup Demo"
        self.market_analysis = MockMarketAnalysis()

class MockMarketAnalysis:
    def __init__(self):
        self.market_size = 5000000000

class MockInvestorPreferences:
    def __init__(self, founder_weight=0.25, market_weight=0.25, differentiation_weight=0.25, traction_weight=0.25, risk_tolerance="medium"):
        self.founder_weight = founder_weight
        self.market_weight = market_weight
        self.differentiation_weight = differentiation_weight
        self.traction_weight = traction_weight
        self.risk_tolerance = risk_tolerance

def main():
    st.set_page_config(
        page_title="AI Startup Evaluator",
        page_icon="🚀",
        layout="wide"
    )
    
    st.title("🚀 AI Startup Evaluator")
    st.markdown("*Automated startup curation and investment analysis powered by Google AI*")
    
    # Add demo notice
    st.info("💡 This is a demo version. The AI analysis is simulated for testing purposes.")
    
    # Sidebar for investor preferences
    with st.sidebar:
        st.header("⚙️ Investor Preferences")
        
        founder_weight = st.slider("Founder Weight", 0.0, 1.0, 0.25, 0.05)
        market_weight = st.slider("Market Weight", 0.0, 1.0, 0.25, 0.05)
        diff_weight = st.slider("Differentiation Weight", 0.0, 1.0, 0.25, 0.05)
        traction_weight = st.slider("Traction Weight", 0.0, 1.0, 0.25, 0.05)
        
        # Normalize weights
        total_weight = founder_weight + market_weight + diff_weight + traction_weight
        if total_weight > 0:
            founder_weight /= total_weight
            market_weight /= total_weight
            diff_weight /= total_weight
            traction_weight /= total_weight
        
        risk_tolerance = st.selectbox("Risk Tolerance", ["low", "medium", "high"])
        
        preferences = MockInvestorPreferences(
            founder_weight=founder_weight,
            market_weight=market_weight,
            differentiation_weight=diff_weight,
            traction_weight=traction_weight,
            risk_tolerance=risk_tolerance
        )
        
        st.markdown("---")
        st.markdown("**Current Weights:**")
        st.write(f"• Founder: {founder_weight:.0%}")
        st.write(f"• Market: {market_weight:.0%}")
        st.write(f"• Differentiation: {diff_weight:.0%}")
        st.write(f"• Traction: {traction_weight:.0%}")
    
    # Main content tabs
    tab1, tab2, tab3 = st.tabs(["📊 Single Evaluation", "📈 Batch Analysis", "📋 Sample Data"])
    
    with tab1:
        st.header("Single Startup Evaluation")
        
        col1, col2 = st.columns([1, 1])
        
        with col1:
            st.subheader("📝 Data Input")
            
            # File upload
            uploaded_file = st.file_uploader("Upload Pitch Deck (PDF)", type=['pdf'])
            if uploaded_file:
                st.success(f"✅ Uploaded: {uploaded_file.name}")
            
            # Form data input
            st.subheader("Or Enter Startup Details")
            
            with st.form("startup_form"):
                company_name = st.text_input("Company Name", placeholder="e.g., TechCorp AI")
                
                col_a, col_b = st.columns(2)
                with col_a:
                    problem_statement = st.text_area("Problem Statement", placeholder="What problem does this startup solve?")
                    market_size = st.number_input("Market Size ($)", min_value=0, value=1000000000, format="%d")
                    employees = st.number_input("Team Size", min_value=0, value=5)
                
                with col_b:
                    solution = st.text_area("Solution", placeholder="How does the startup solve this problem?")
                    revenue = st.number_input("Annual Revenue ($)", min_value=0, value=0, format="%d")
                    funding_stage = st.selectbox("Funding Stage", ["Pre-seed", "Seed", "Series A", "Series B", "Series C+"])
                
                submitted = st.form_submit_button("🔍 Evaluate Startup", type="primary")
                
            if submitted and company_name:
                try:
                    with st.spinner("🤖 Analyzing startup... This may take a few moments."):
                        evaluator = MockStartupEvaluator()
                        
                        # Simulate processing time
                        import time
                        time.sleep(2)
                        
                        # Evaluate
                        memo = evaluator.evaluate_startup(
                            pitch_deck_path=uploaded_file.name if uploaded_file else None,
                            form_data={
                                "company_name": company_name,
                                "problem_statement": problem_statement,
                                "solution": solution,
                                "market_size": market_size,
                                "revenue": revenue,
                                "employees": employees
                            },
                            investor_preferences=preferences
                        )
                        
                        # Store in session state
                        st.session_state['current_memo'] = memo
                        st.success("✅ Analysis completed!")
                        
                except Exception as e:
                    st.error(f"❌ Error during evaluation: {str(e)}")
        
        with col2:
            st.subheader("📊 Analysis Results")
            
            if 'current_memo' in st.session_state:
                memo = st.session_state['current_memo']
                
                # Key metrics in columns
                col_a, col_b, col_c = st.columns(3)
                
                with col_a:
                    st.metric("Investment Score", f"{memo.investment_score:.1f}/10", delta="7.8")
                
                with col_b:
                    st.metric("Risk Level", memo.risk_assessment.risk_level.upper())
                
                with col_c:
                    rec_short = memo.recommendation.split(" - ")[0]
                    st.metric("Recommendation", rec_short)
                
                # Full recommendation
                st.markdown(f"**Full Recommendation:** {memo.recommendation}")
                
                # Key insights
                col_a, col_b = st.columns(2)
                with col_a:
                    st.markdown("**✨ Key Strengths:**")
                    for strength in memo.key_strengths:
                        st.markdown(f"• {strength}")
                
                with col_b:
                    st.markdown("**⚠️ Key Concerns:**")
                    for concern in memo.key_concerns:
                        st.markdown(f"• {concern}")
                
                # Risk factors if any
                if memo.risk_assessment.risk_factors:
                    st.markdown("**🚨 Risk Factors:**")
                    for risk in memo.risk_assessment.risk_factors:
                        st.markdown(f"• {risk}")
                
                # Deal note
                if st.button("📄 Generate Deal Note", type="secondary"):
                    try:
                        evaluator = MockStartupEvaluator()
                        deal_note = evaluator.generate_deal_note(memo)
                        st.markdown("### 📝 Investment Deal Note")
                        st.markdown(deal_note)
                        
                        # Download button
                        st.download_button(
                            label="⬇️ Download Deal Note",
                            data=deal_note,
                            file_name=f"deal_note_{memo.startup_profile.company_name.replace(' ', '_')}.md",
                            mime="text/markdown"
                        )
                    except Exception as e:
                        st.error(f"Error generating deal note: {str(e)}")
            else:
                st.info("👆 Enter startup details and click 'Evaluate Startup' to see results")
    
    with tab2:
        st.header("Batch Analysis")
        st.info("📊 Upload multiple startup data files for batch processing")
        
        # Sample batch data
        if st.button("🚀 Run Sample Batch Analysis", type="primary"):
            sample_data = [
                {"form_data": {"company_name": "TechStartup A"}},
                {"form_data": {"company_name": "HealthTech B"}},
                {"form_data": {"company_name": "FinTech C"}}
            ]
            
            try:
                with st.spinner("🔄 Processing batch analysis... This may take a few minutes."):
                    evaluator = MockStartupEvaluator()
                    import time
                    time.sleep(3)  # Simulate processing
                    
                    results = evaluator.batch_evaluate(sample_data, preferences)
                    
                    # Display results table
                    df_data = []
                    for i, memo in enumerate(results):
                        df_data.append({
                            "Company": f"Sample Company {chr(65+i)}",
                            "Score": f"{memo.investment_score:.1f}/10",
                            "Recommendation": memo.recommendation.split(" - ")[0],
                            "Risk": memo.risk_assessment.risk_level.upper(),
                            "Market Size": f"${memo.startup_profile.market_analysis.market_size/1e9:.1f}B"
                        })
                    
                    df = pd.DataFrame(df_data)
                    st.dataframe(df, use_container_width=True)
                    st.success(f"✅ Analyzed {len(results)} startups successfully!")
                    
            except Exception as e:
                st.error(f"❌ Error in batch analysis: {str(e)}")
    
    with tab3:
        st.header("Sample Data & Testing")
        
        st.subheader("📋 Sample Form Data")
        sample_form = {
            "company_name": "AI Analytics Corp",
            "problem_statement": "Businesses struggle with data-driven decision making due to complex analytics tools",
            "solution": "No-code AI analytics platform that generates insights automatically",
            "market_size": 15000000000,
            "revenue": 1200000,
            "employees": 25,
            "funding_stage": "Series A",
            "funding_amount": 5000000
        }
        
        st.json(sample_form)
        
        if st.button("🧪 Test with Sample Data", type="primary"):
            try:
                with st.spinner("🔬 Testing evaluation..."):
                    evaluator = MockStartupEvaluator()
                    import time
                    time.sleep(1)
                    
                    memo = evaluator.evaluate_startup(form_data=sample_form, investor_preferences=preferences)
                    
                    st.success("✅ Evaluation completed!")
                    
                    col1, col2, col3 = st.columns(3)
                    with col1:
                        st.metric("Investment Score", f"{memo.investment_score:.1f}/10")
                    with col2:
                        st.metric("Risk Level", memo.risk_assessment.risk_level.upper())
                    with col3:
                        st.metric("Recommendation", memo.recommendation.split(" - ")[0])
                        
            except Exception as e:
                st.error(f"❌ Error in sample evaluation: {str(e)}")
        
        # Architecture info
        st.markdown("---")
        st.subheader("🏗️ System Architecture")
        st.markdown("""
        **Multi-Agent System:**
        - 🤖 **Data Extraction Agent**: Processes pitch decks and forms
        - 🗺️ **Mapping Agent**: Structures data into startup profiles
        - 📊 **Analysis Agent**: Generates investment scores
        - 🌐 **Public Data Agent**: Enriches with market data
        
        **Scoring Framework:**
        - Founder-Market Fit (0-10)
        - Market Opportunity (0-10) 
        - Differentiation (0-10)
        - Traction Metrics (0-10)
        """)

if __name__ == "__main__":
    main()